### Lý thuyết

In [10]:
import numpy as np

# Tạo mảng 1D ( vector )
a = np.array([1, 2, 3, 4])
print(f"a: {a}")

# Tạo mảng 2D (ma trận)
b = np.array([[1, 2], [3, 4]])
print(f"b: \n{b}")

# Tạo mảng số 0, số 1 và mảng ngẫu nhi ên
zero_matrix = np.zeros((3, 3))
print(f"zero_matrix: \n{zero_matrix}")
ones_matrix = np.ones((2, 2))
print(f"ones_matrix: \n{ones_matrix}")
rand_matrix = np.random.rand(3, 3)
print(f"rand_matrix: \n{rand_matrix}")

# Tạo ma trận đơn vị
identity_matrix = np.eye(3)
print(f"identity_matrix: \n{identity_matrix}")

a: [1 2 3 4]
b: 
[[1 2]
 [3 4]]
zero_matrix: 
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
ones_matrix: 
[[1. 1.]
 [1. 1.]]
rand_matrix: 
[[0.4816044  0.27659551 0.05710078]
 [0.88745288 0.73522115 0.31593835]
 [0.29278153 0.68938446 0.60905962]]
identity_matrix: 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### Phép Cộng, Trừ Hai Ma Trận

In [12]:
A = np . array ([[1 , 2] , [3 , 4]])
B = np . array ([[5 , 6] , [7 , 8]])

C = A + B # Cộng ma trận
D = A - B # Trừ ma trận

print(f"C: \n{C}")
print(f"D: \n{D}")

C: 
[[ 6  8]
 [10 12]]
D: 
[[-4 -4]
 [-4 -4]]


####  Phép Nhân Từng Phần Tử (Element-wise)

In [13]:
E = A * B # Nhân từng phần tử

print(f"E: \n{E}")

E: 
[[ 5 12]
 [21 32]]


####  Phép Nhân Ma Trận (Matrix Multiplication)

In [15]:
C_1 = A @ B 
C_2 = np.dot(A, B)

print(f"C_1: \n{C_1}")
print(f"C_2: \n{C_2}")

C_1: 
[[19 22]
 [43 50]]
C_2: 
[[19 22]
 [43 50]]


#### Định Thức Ma Trận

In [ ]:
det_A = np.linalg.det(A)

print(f"det_A: {det_A}")

det_A: -2.0000000000000004


#### Ma Trận Nghịch Đảo

In [19]:
A_inv = np.linalg.inv(A)

print(f"A_inv: \n{A_inv}")

A_inv: 
[[-2.   1. ]
 [ 1.5 -0.5]]


#### Hạng của Ma Trận

In [21]:
rank_A = np.linalg.matrix_rank(A)

print(f"rank_A: {rank_A}")

rank_A: 2


#### Giải Hệ Phương Trình Tuyến Tính

In [23]:
x = np.linalg.solve(A, B)

print(f"x: \n{x}")

x: 
[[-3. -4.]
 [ 4.  5.]]


#### Tính Giá Trị Riêng và Vector Riêng


In [25]:
eig_values, eig_vectors = np.linalg.eig(A)

print(f"eig_values: \n{eig_values}")
print(f"eig_vectors: \n{eig_vectors}")

eig_values: 
[-0.37228132  5.37228132]
eig_vectors: 
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


####  Phân Rã SVD (Singular Value Decomposition)


In [27]:
U, S, V = np.linalg.svd(A)

print(f"U: \n{U}")
print(f"S: \n{S}")
print(f"V: \n{V}")

U: 
[[-0.40455358 -0.9145143 ]
 [-0.9145143   0.40455358]]
S: 
[5.4649857  0.36596619]
V: 
[[-0.57604844 -0.81741556]
 [ 0.81741556 -0.57604844]]


#### Tích Vô Hướng (Dot Product)


In [ ]:
dot_product = np.dot(v1, v2)

print(f"dot_product: {dot_product}")

####  Tích Có Hướng (Cross Product)

In [ ]:
cross_product = np.cross(v1, v2)

print(f"cross_product: {cross_product}")

#### Chuẩn của Vector (Norm)


In [ ]:
norm_v = np.linalg.norm(v)

#### Chuyển Vị Ma Trận

In [ ]:
A_transpose = A.T

print(f"A_transpose: {A_transpose}")

### Bài tập

#### Bài 1

In [35]:
A = np.array([[1, 2], [3, 4]])

B = np.array([[5, 6], [7, 8]])

In [36]:
C = A + B
D = A - B

print(f"C: \n{C}")
print(f"D: \n{D}")

C: 
[[ 6  8]
 [10 12]]
D: 
[[-4 -4]
 [-4 -4]]


#### Bài 2

In [41]:
C = np.array([[2, -3], [4, -5]])

D = np.array([[1, 4], [-2, 6]])

print(f"C + D: \n{C + D}")
print(f"C - D: \n{C - D}")

C + D: 
[[3 1]
 [2 1]]
C - D: 
[[  1  -7]
 [  6 -11]]


#### Bài 3

In [44]:
A = np.array([[1, 2], [3, 4]])

B = np.array([[5, 6], [7, 8]])

print(f"A * B: \n{A * B}")

A * B: 
[[ 5 12]
 [21 32]]


#### Bài 4

In [43]:
E = np.array([[0, 1, 2], [3, 4, 5]])
F = np.array([[5, 4, 3], [2, 1, 0]])

print(f"E * F: \n{E * F}")

E * F: 
[[0 4 6]
 [6 4 0]]


#### Bài 5

In [48]:
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

dot_product = np.dot(v1, v2)
print(f"v1 * v2: {dot_product}")

v1 * v2: 32


#### Bài 6

In [49]:
def convolution(matrix, kernal): 
    kernal_h = len(kernal)
    kernal_w = len(kernal[0])

    mat_h = len(matrix)
    mat_w = len(matrix[0])

    result = []

    for i in range(mat_h - kernal_h + 1):
        row = []
        for j in range(mat_w - kernal_w + 1):
            sum_value = 0
            for ki in range(kernal_h):
                for kj in range(kernal_w):
                    sum_value += matrix[i + ki][j + kj] * kernal[ki][kj]
            row.append(sum_value)
        result.append(row)
    
    return result

In [52]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[1, 0], [0, -1]])

C = convolution(A, B)
C = np.array(C)
print(f"C: \n{C}")

C: 
[[-4 -4]
 [-4 -4]]


#### Bài 8

In [ ]:
v = np.array([1, 0])

theta = 45

rotation_matrix = np.array([[np.cos(theta), np.sin(theta)], 
                            [-np.sin(theta), np.cos(theta)]])

v_rotated = np.dot(v, rotation_matrix)

print(f"v_rotated: {v_rotated}")

v_rotated: [0.52532199 0.85090352]
