#### Bài 1

In [13]:
import numpy as np

def compute_gram_matrix(feature_map: np.ndarray) -> np.ndarray:
    C, H, W = feature_map.shape

    F = feature_map.reshape(C, H*W)

    G = np.dot(F, F.T)

    G = G.astype(float)
    G /= (H*W)

    return G

np.random.seed(42)
feature_map = np.random.rand(3, 4, 4)

# Tính Gram Matrix
gram_matrix = compute_gram_matrix(feature_map)
print(gram_matrix)

[[0.33432857 0.2207897  0.27598961]
 [0.2207897  0.19580158 0.19452994]
 [0.27598961 0.19452994 0.32603015]]


In [14]:
feature_map = np.array([
    [[1, 2], [3, 4]], 
    [[5, 6], [7, 8]], 
    [[9, 10], [11, 12]] 
])

gram_matrix = compute_gram_matrix(feature_map)
print(gram_matrix)

[[  7.5  17.5  27.5]
 [ 17.5  43.5  69.5]
 [ 27.5  69.5 111.5]]


#### Bài 2

In [ ]:
def compute_similarity(gram1: np.ndarray, gram2:np.ndarray) -> float:
    """
    Tính độ tương đồng giữa hai Gram Matrix.

    Args:
    gram1(np.ndarray): Gram Matrix ảnh 1.
    gram2(np.ndarray): Gram Matrix ảnh 2.

    Returns:
    float: Độ tương đồng trong kho ảnh [0, 1].
    """
    # Your code here #
    up = np.sum(gram1*gram2)
    down = (np.sqrt(np.sum(gram1**2)))*(np.sqrt(np.sum(gram2**2)))

    similarity = up/down
    return similarity

# Feature Map của hai ảnh
feature_map1 = np.array ([
[[1, 2], [3, 4]],
[[5, 6], [7, 8]],
[[9, 10], [11, 12]]
])

feature_map2 = np.array ([
[[2, 4], [6, 8]],
[[1, 3], [5, 7]],
[[0, 2], [4, 6]]
])

# Tính Gram Matrix của hai ảnh
gram1 = compute_gram_matrix(feature_map1)
gram2 = compute_gram_matrix(feature_map2)

# Tính độ tương đồng
similarity = compute_similarity(gram1, gram2)
print(" Similarity Score :", similarity)

 Similarity Score : 0.6741245785155123
